services:
  - type: web
    name: food-waste-management-server
    env: node
    plan: free
    buildCommand: npm install && npm run prisma:generate
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
